name: "tests"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fmt:
    name: "Fmt"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --check

  css:
    name: "CSS"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 25
        uses: actions/setup-node@v4
        with:
          node-version: 25
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm run build

      - name: Upload CSS to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: css-build-output
          path: dist/style.css
          retention-days: 1

  clippy:
    name: "Clippy"
    needs: [css]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: css-build-output
          path: ./dist
      - name: Linting
        run: cargo clippy -- -D warnings

  test:
    name: "Test"
    needs: [fmt, clippy, css]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: css-build-output
          path: ./dist
      - name: Run tests
        run: cargo test

  tarpaulin:
    name: "Tarpaulin"
    runs-on: ubuntu-latest
    needs: [test, css]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: css-build-output
          path: ./dist
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Run tarpaulin
        run: cargo tarpaulin
